package main

import (
	"fmt"
	"os"
)

const (
	TEST_DIRECTORY = "testing_files"
)

var INDENT string = "  "
var RESULT string = "type autoGenerated struct {\n"

func main() {
	//fmt.Printf("Hello,world!\n")
	//file, err := os.Open(TEST_DIRECTORY + "/" + "one.json")
	//if err != nil {
	//	fmt.Println("err : ", err)
	//	os.Exit(1)
	//}

	fmt.Println("---------------------------")
	fileContent, err := os.ReadFile(TEST_DIRECTORY + "/" + "one.json")
	if err != nil {
		fmt.Println("err : ", err)
		os.Exit(1)
	}

	tokens, err := Tokenize(string(fileContent))
	if err != nil {
		fmt.Println("err : ", err)
		os.Exit(1)
	}
	for _, tr := range tokens {
		for _, t := range tr {
			fmt.Printf("%v  ", t)
		}
		fmt.Println()
	}

	//var emptyInterface interface{}
	//decoder := json.NewDecoder(file)
	//err = decoder.Decode(&emptyInterface)
	//
	//if err != nil {
	//	fmt.Println("err : ", err)
	//	os.Exit(1)
	//}
	//fmt.Println("Interface -> ", emptyInterface)
}
